print("welcome to the youtube channel name generator")
user_name = input("what is your nickname?\n")
about = input("what is your channel about?\n")
print("\nhere are 3 channel name ideas:\n")
print("1. " +(about)+(" with "+(user_name)))
print("2. "+(user_name)+(" tv "))
print("3. "+(user_name)+(" official "))
